//
// Created by user on 21.05.2023.
//

#ifndef MINIMAL_DOMINATING_SET_MINIMAL_DOMINATING_SET_H
#define MINIMAL_DOMINATING_SET_MINIMAL_DOMINATING_SET_H

#endif  //MINIMAL_DOMINATING_SET_MINIMAL_DOMINATING_SET_H
